name: verify

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/kmyk/online-judge-verify-helper
      
    # if you want to verify csharp script file.
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'  # SDK Version to use.
    - name: Install dependencies (C#)
      run: dotnet tool install -g dotnet-script

    - name: Check env
      run: echo $PATH

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
